spring:
  application:
    name: payments-integration
  main:
    allowBeanDefinitionOverriding: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:payments-integration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  flyway:
    table: schema_version

transwerwise:
  ribbon:
    listOfServers: api.sandbox.transferwise.tech:443
